apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: ikulyk404/busyboxplus:curl
              command:
                - /bin/sh
                - -c
                - "curl -s http://todoapp-service/api/health"
              resources:
                requests:
                  cpu: "100m"
                  memory: "50Mi"
                limits:
                  cpu: "200m"
                  memory: "100Mi"
          restartPolicy: OnFailure


